apiVersion: skaffold/v1beta3
kind: Config
metadata:
  name: hello-cloudbuild-app
build:
  artifacts:
  - image: us-central1-docker.pkg.dev/gke-anthos-poc/my-repository/hello-cloudbuild
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - delivery-pipeline.yaml
   # - target_dev.yaml
    - hello-cloudbuild-app/kubernetes.yaml
